import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = LocalFont({
  src: [
    {
      path: "../../node_modules/@velocity/assets/src/fonts/Lora-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../node_modules/@velocity/assets/src/fonts/Lora-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../node_modules/@velocity/assets/src/fonts/Lora-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../node_modules/@velocity/assets/src/fonts/Lora-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-lora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
